---
root: true

plugins:
  - babel

env:
  browser: true
  node: true

extends:
  - 'eslint:recommended' 
  - 'airbnb-base' 
  - 'plugin:import/recommended'

parser: '@babel/eslint-parser'

rules:
  no-console: 0
  import/extensions: 0
